package com.levayb;

public class Main {

    public static void main(String[] args) {
        // The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number
        // would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
        //
        //1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
        //
        //Let us list the factors of the first seven triangle numbers:
        //
        // 1: 1
        // 3: 1,3
        // 6: 1,2,3,6
        //10: 1,2,5,10
        //15: 1,3,5,15
        //21: 1,3,7,21
        //28: 1,2,4,7,14,28
        //We can see that 28 is the first triangle number to have over five divisors.
        //
        //What is the value of the first triangle number to have over five hundred divisors?

        int i = 1;
        while (numberOfDivisors(generateTriangleNumber(i)) <= 500) {
            i++;
        }
        System.out.println(generateTriangleNumber(i));
    }

    private static int generateTriangleNumber(int index) {
        int result = 0;
        for (int i = 1; i <= index; i++) {
            result += i;
        }
        return result;
    }

    private static int numberOfDivisors(int number) {
        if (number == 1) {
            return 1;
        }
        int result = 2;
        for (int i = 2; i <= (number / 2); i++) {
            if (number % i == 0) {
                result++;
            }
        }
        return result;
    }
}
