package com.levayb;

public class Main {

    public static void main(String[] args) {
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        //By starting with 1 and 2, the first 10 terms will be:
        //
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //
        //By considering the terms in the Fibonacci sequence whose values
        //do not exceed four million, find the sum of the even-valued terms.

        int fibNum1 = 0;
        int fibNum2 = 1;
        int newFib = 0;
        int result = 0;
        while (newFib < 4000000){
            newFib = fibNum1 + fibNum2;
            fibNum1 = fibNum2;
            fibNum2 = newFib;
            if (newFib % 2 == 0){
                result = result + newFib;
            }
        }
        System.out.println(result);



        // int result = 0;
        //  int firstNumber = 0;
        // int secondNumber = 1;
        // int finalNumber = 4000000;

        // boolean fibNumber = false;

        //  while (!fibNumber) {
        //  int newFib = (firstNumber + secondNumber);
        //   firstNumber = secondNumber;
        //  secondNumber = newFib;

        //     if (newFib > finalNumber){
        //       fibNumber = true;
        //       break;
        //  }
        //   if (newFib % 2 == 0){
        //       result = result + newFib;

        //  }

    }


    //   System.out.println(result);

}
